### ISSUE TITLE
RahmanAlgorithm simga is out of range

### ISSUE THREAD

**Issue by s-wtnb** [tatsy/ColorConstancy#1]
Hi.
It is great library!

https://github.com/tatsy/ColorConstancy/blob/master/RahmanAlgorithm/main.cpp#L45
```
	ns = 3; 
	vector<float> sigmas = vector<float>(ns);
	sigmas[0] = sigma * (float)max(height, width);
	for(int i=1; i<=ns; i++) sigmas[i] = sigmas[i-1] * scale;
```
simga[3] is out of range.

```
	for(int i=1; i<ns; i++) sigmas[i] = sigmas[i-1] * scale;
```
= looks unnecessary.

**Comment by tatsy** [comment]
Hi @s-wtnb, 
You are right. Thank you for your advice.
